[project]
name = "todoapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "bcrypt==4.0.1",
    "fastapi[standard]>=0.141.1",
    "httpx2>=2.12.0",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "pymysql>=1.2.0",
    "pytest>=9.1.1",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = """
    --log-cli-format='[%(asctime)s.%(msecs)03d][%(levelname)s] %(message)s' \
    --log-cli-level=INFO \
"""

[tool.ruff]
line-length = 120